Topological fixed point finder
deveres99/xnlbd pull request #11
Opened 2024-08-19 14:55 UTC by deveres99

I added the implementation of a fixed point finder adapted from the generalised bisection algorithm of M. Vrahatis. This is capable of finding accurately both stable and unstable fixed points. I added tests for cases of a real lattice as well as a Henon map in both 2D and 4D, and there are examples illustrating how to apply the tool and how it works on both real lattice and Henon map in both 2D and 4D.

2024-08-19 19:35 UTC, majorpeti007 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
**nit**: Move this check out of the branches to before the if-elif condition.

2024-08-19 19:35 UTC, majorpeti007 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            fp_coords_norm = {
**nit**: Setting `fp_coords_norm` and `fp_coords` is the same in all branches, move it to after the if-elif condition.

2024-08-19 19:35 UTC, majorpeti007 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
**nit**: Move check to before if-elif.

2024-08-19 19:35 UTC, majorpeti007 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
**nit**: Move check earlier.

2024-08-19 19:35 UTC, majorpeti007 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        while np.any(np.isnan(init_n_poly)):
**issue**: Potentially never ending while.

2024-08-19 19:44 UTC, majorpeti007 requested changes
Please see detailed comments on suggested changes.

2024-08-20 06:09 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +import xpart as xp  # type: ignore[import-untyped]
Removed!

2024-08-20 06:10 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        co_guess: dict[str, float] = {
I changed default to None

2024-08-20 06:10 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        self.edges: list[Tuple] = self._construct_edges()
Applied

2024-08-20 06:10 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +    def _construct_edges(self) -> list[Tuple]:
Applied

2024-08-20 06:11 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        co_guess: dict[str, float] = {
Changed default to None

2024-08-20 06:11 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        co_guess: dict[str, float] = {
Changed default to None

2024-08-20 06:12 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        limits: list[list],
Proper typing done, but I kept it as a list of lists

2024-08-20 06:13 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        nemitt_x=1e-6,
Typing added

2024-08-20 06:13 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +    ) -> Tuple[dict, dict]:
Added typing

2024-08-20 06:14 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
Done!

2024-08-20 06:14 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            fp_coords_norm = {
Done!

2024-08-20 06:15 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
I don't see this one, because in each branch I perform the check on a different particle object. How could I remove and unify this?

2024-08-20 06:17 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
I don't see this one, because in each branch I perform the check on a different particle object. How could I remove and unify this?

2024-08-20 06:17 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
I don't see this one, because in each branch I perform the check on a different particle object. How could I remove and unify this?

2024-08-20 06:17 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
I don't see this one, because in each branch I perform the check on a different particle object. How could I remove and unify this?

2024-08-20 06:17 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +            if not isinstance(self.gbs_part, Particles) or not isinstance(
I don't see this one, because in each branch I perform the check on a different particle object. How could I remove and unify this?

2024-08-20 06:18 UTC, deveres99 commented on xnlbd/visualise/fixed_points/topological_fixed_point_finder.py
> +        while np.any(np.isnan(init_n_poly)):
I added a stopping condition.

2024-08-20 15:29 UTC, majorpeti007 approved these changes

2024-08-20 15:39 UTC, merged