Fix missing elements in ModulatedHenonMap
deveres99/xnlbd pull request #2
Opened 2024-07-10 14:56 UTC by carlidel

There was actually a couple of missing elements in the ModulatedHenonMap.
This is actually the version I have been using so far.

Note the extra changes to make the loop over different indices for the modulations and for the kick coefficients.

Also other minor changes:

- add a little function reporting the "standard" SPS modulation for the Hénon map;
- change the header guards in the c source to the new package name

2024-07-14 10:23 UTC, deveres99 requested changes
I have reviewed the changes, thanks for adding the different coefficient modulation, in general everything looks good, I just requested a few minor changes in docstrings here and there and a variable name change in the modulations.py file.

2024-07-14 10:23 UTC, deveres99 commented on xnlbd/track/elements.py
In the docstring, can you please add the new parameter "n_par_multipoles" under the section "Comments", similarly to the "n_turns" one?

2024-07-14 10:23 UTC, deveres99 commented on xnlbd/track/modulations.py
> +        1 * (2 * np.pi / 868.12),
I would extract the `868.12` into its own constant, something like e.g. `SPS_REV_FREQ_IN_TURNS`, so it is clear what it is not just there as magic number.

2024-07-14 10:23 UTC, deveres99 commented on xnlbd/track/modulations.py
> +# REF: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.57.3432
Can you maybe add a short comment here above the REF comment along the lines of "Amplitude of different 50 Hz harmonics measured in the SPS tune modulation as described in" followed by your link to the reference

2024-07-14 10:23 UTC, deveres99 commented on xnlbd/track/modulations.py
> +def make_sps_modulation(base_tune, epsilon, times=np.arange(86812)):
I would change `times` to `turns`, because the frequency is in 1/turns, so you evaluate the modulation at given turns and not given times. Also change in the docstring.

2024-07-14 15:21 UTC, carlidel commented on xnlbd/track/modulations.py
> +def make_sps_modulation(base_tune, epsilon, times=np.arange(86812)):
Done!

2024-07-14 15:21 UTC, carlidel commented on xnlbd/track/modulations.py
> +# REF: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.57.3432
Done!

2024-07-14 15:21 UTC, carlidel commented on xnlbd/track/modulations.py
> +        1 * (2 * np.pi / 868.12),
Done!

2024-07-14 15:21 UTC, carlidel commented on xnlbd/track/elements.py
Done!

2024-07-15 15:44 UTC, deveres99 approved these changes
Looks good, thanks!

2024-08-03 13:47 UTC, merged